version: 0.2

phases:
    install:
        runtime-versions:
            python: 3.8
        commands:
            - echo "Installing dependencies..."
    pre_build:
        commands:
            - echo "Pre-build setup"
    build:
        commands:
            - echo "Building..."
    post_build:
        commands:
            - echo "Post build"
